keys:
creation_rules:
  - path_regex: secrets/.*$
    key_groups:
      - age:
        - age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf
        - age1efdgqxst6zk3vysvnmrexuh9csqwz9nwhtr9uyp77xn8epddvcuskq8y9v
