#ENC[AES256_GCM,data:o/gQlZB7BkRI8WYTU4+JEUKRRDw2AkWVhsGP4e7PR2ZmHQ==,iv:tjwQ4DeGjZVxV69eEMVEQBkJ57lLO9K8HwFg1MQdwhU=,tag:n1+aj9A2MRaHyzEt8x6tBg==,type:comment]
#ENC[AES256_GCM,data:UN3TNIQ7XjxmTcqe5ZyzxzYvHNov5FiLuRDXzyRdQev+yJjpxUTfzNDLDYxSK44=,iv:zAZsNn7PLpPq88c9yuVJJ900jFCMIXH+IAv2rQmU1e4=,tag:L1NuSYhn8eOMXDtMQTCd9A==,type:comment]
#ENC[AES256_GCM,data:w9Np8lg/qwP6yPBlPwhyBPzPVmWvQg3LgsUy4DWURg==,iv:hJ3X1Oxz7t7DzO7y+aJCtSVmyoJ7atml2FiLaVFSbAc=,tag:j4JJufLPNt2EHpMzrTPbGQ==,type:comment]
pki:
    ca: ENC[AES256_GCM,data:jbtFcB1yzhWtE4Q885yzn+Liu8T4xkjvTB8PqHaGvQUcdiuY,iv:wpLyADSr9Sv/N+c/4VBSx/Ske8wkSXsEIA+mNg9lTKU=,tag:dWLz9RsRWaod2Qe+U1EhTw==,type:str]
    cert: ENC[AES256_GCM,data:QOg7uv0S00Rb6wnpoHp6GVZlgt1y9N14M67Hs8F/BNwSYdlRhmU=,iv:YFpsuq2aDoWc+jJXpu0U0hH8IvsA57a8e/B6kHdF17g=,tag:93i97uiP22wYfrrhfOxMPw==,type:str]
    key: ENC[AES256_GCM,data:VnbOm56Zp1k8SbQXbTBQ0BHowSazqeGKvRJXLl+ZNxdhqlfc2zo=,iv:D3LIln7HFln8nQyhFRbyROQSycard4QHSTBGjEn1ETI=,tag:3WtMOXpRLBgEjILP/ll4TA==,type:str]
static_host_map:
    10.10.10.10:
        - ENC[AES256_GCM,data:pQFw9AGuHbcarJfaFZkRR4bL,iv:RhwVjrMi+8JH/6QU6UprNdoB/RF4CQMyTYkY1xBZ18s=,tag:PHg02EmrgJ8HV6uuDtPUmg==,type:str]
    10.10.10.11:
        - ENC[AES256_GCM,data:265usJIaNDpTOU2yrt2wx7ML,iv:6vN6AqpoFDXRaPLOD3ysDlXI1XVH7laVExBMZkiSBE0=,tag:UQ8fZE1xNkLmrpEu4Aa+Hw==,type:str]
    10.10.10.12:
        - ENC[AES256_GCM,data:suHSwPHV2a4wb4Smcw7yzGU=,iv:4RmK5/fFdqEEbGcqQ6nmQ9kH6VbHKQSk22jqRWXYj88=,tag:Meeo5zoJMmrM6YDuJmYk9g==,type:str]
lighthouse:
    am_lighthouse: ENC[AES256_GCM,data:3sDSB48=,iv:rLCRnXp/t5mY1QxTGVJjw3PC36xSmj4W7ztQkn2pNfA=,tag:8d4s9flO0fnpgQ9wY2r+Tg==,type:bool]
    interval: ENC[AES256_GCM,data:H1E=,iv:LFA140Ew/1BRIS2URSOH+gZYhbjSd1QcfIpKUOAjqP8=,tag:O4tmIVry1/jmtxP4TMSzGw==,type:int]
    hosts:
        - ENC[AES256_GCM,data:5X4FMXmtXMvCCFw=,iv:6uoVvA8UYI5okBEusW/ze7Xu8nqPXOje5ohPzPEykRE=,tag:Iu8jLylWJ4xKpayk8g80hw==,type:str]
        - ENC[AES256_GCM,data:5wSkqe+Tef58AtY=,iv:vcvKvYA1NS2cxbarUy3bAGpx8WibfNyquEXW1mdkdiw=,tag:b6EUYWupOiGwYljcpBkVkQ==,type:str]
        - ENC[AES256_GCM,data:VM2hOH8ynQAQJxU=,iv:Jz93w5cUq8tukTiiCzE1nFP0LsAz3WqoohKdLC1yF3A=,tag:ENb8GBB0ipiAI4/Rkfksgw==,type:str]
listen:
    host: ENC[AES256_GCM,data:wCCMcNB3Kw==,iv:2rTE+7VDsewks15sJeA38a7jyBIUIrZ02bEzLgtAT6k=,tag:BXl2kd5t8cQsSyR6jMQkow==,type:str]
    port: ENC[AES256_GCM,data:KzUgng==,iv:S14Soo6shiMb62iu8V5jA5FaqDGGU0PPd+/YIqUpub4=,tag:rKBw6+uJ9NxjlQZSo4vznQ==,type:int]
punchy:
    punch: ENC[AES256_GCM,data:+4pPjg==,iv:p3C1oCkOjZuuZtwZ1iGBWj7sFsA9bgczc0fdDVRwWX0=,tag:dltcy4wHkGegf2ZL+/laOA==,type:bool]
    respond: ENC[AES256_GCM,data:G5vdNw==,iv:GcM50YD5k5edNjKusOlOzAdsw+TBjhKxtO647ZcYHjs=,tag:oTqx2wMA/JKiSuYfD89czw==,type:bool]
#ENC[AES256_GCM,data:0pqRZh1wvGbPUCA2MDxQDDpa6VQP2AIF5trxNxOcepnt2cp/u0rgBMQdfQ08SpKWpc5D,iv:5kUKCPNGd65696OZfvrV12/yGlXdrgVoNcQrz0indlQ=,tag:hVlqBizB2ZosAhSYwJStog==,type:comment]
cipher: ENC[AES256_GCM,data:OUksKzC6/KpfdQ==,iv:bz4QPmqxuCz3UvVoJGtncLKjPDwftnai702o2vpeixk=,tag:mdvhJSSl3q7qIupwnzP4cg==,type:str]
#ENC[AES256_GCM,data:iR6TrIZXdHBegAntM/J5ctWhunEGG35gj8uzpn7Qs6i8Uw8hvOY=,iv:1zAp2ka9MTtJNs59FDx0YjC69KuZsth/F3GWdgjGs3s=,tag:NGQU89fWk4fCPf+4Rxijug==,type:comment]
relay:
    am_relay: ENC[AES256_GCM,data:U5lKemI=,iv:BcPalZlI+7REiNRHbjc4OmABeZZV5hKPPXtkzMrat2w=,tag:k4SUX90IZzhgoEPDJ9d2qA==,type:bool]
    use_relays: ENC[AES256_GCM,data:URtftg==,iv:mgCfatsKZzHVNCj2Tg4lV7S7RjR9b5dEnyQyqctFJ6k=,tag:+pHJ7Ym8aIy8YJ+xKkELeg==,type:bool]
#ENC[AES256_GCM,data:HzS73YNzRXY+dc+BhCVLW/dnKg2dj7R2X0aqI8JrF3xF,iv:rI/9ivTgIoymBxN18lc8yfvcAWJBO8iWBofWkTWeh7s=,tag:mamwLM0FjsuS48u3i6zJ9w==,type:comment]
timers:
    connection_alive_interval: ENC[AES256_GCM,data:yCnn,iv:txko0ptnXtWJ05ZuQLuH6JeaOkzlCq2eeDqbJXNrieI=,tag:d/T+AuwbctH6A7EXJO+lDA==,type:str]
    pending_deletion_interval: ENC[AES256_GCM,data:y/3J,iv:V9L1D8+F6l98myf/G7zjnFWCU3IOBuDSD7c46dKc6PM=,tag:ArizJZ8mDnkXyFVvkN79hQ==,type:str]
#ENC[AES256_GCM,data:Wsh26gmp0MleTRbIzpLpqhpusralTFNL8A==,iv:jQpr16Qo7y1zgBPywkzova/tVeuB7+x+yLpXC3J5PlU=,tag:2VWSZ9WB1miaRNH3RNrRAQ==,type:comment]
tun:
    disabled: ENC[AES256_GCM,data:FtZ+ivc=,iv:xEZuiw7GxFu7+8f5k4j30HBmElvyH1ld1gAYQueQhSA=,tag:cgQL2+Nrm7pVqQL6xhy3Hg==,type:bool]
    dev: ENC[AES256_GCM,data:0n7BQb+G,iv:Bwjam2GtjbRfGTzzh6l80i5cScMvBCO+sKyKvjFtr04=,tag:+itz/f2wMOIlvxI7MJcYaQ==,type:str]
    #ENC[AES256_GCM,data:ZKREDwM0TwfWJmKjryIEajU9t0L0GQ5J030+Pzb42jeMelm9WYx360ua5DOITv0/6AIJglBdh+Q=,iv:c0FacEZHMBoX2Zq0QCebO6RkUcdEFZH/hGlh0OyYCmU=,tag:p9o8peQV5Qgm4wU2iVtaPw==,type:comment]
    drop_local_broadcast: ENC[AES256_GCM,data:Bj/7FA==,iv:4rf8+6brOQIVfZvgZUizxx5e0SX49MwIClX3IVYZ7YA=,tag:PlHkfW/ODoQc55kLxF78zQ==,type:bool]
    #ENC[AES256_GCM,data:/L4UgT5RgAMyC7brTHRHhyGccWbdeSJDJrXxridIGoBVwIRDi0CsPptw8AfLdPctRpTGtXqnhyJel/lp2RhV1/Ixv3n7GOQ0AL2Mk2TUEQ==,iv:XsB8xRQPpnB+d5lcCz5YQDE6aNH6CJ9m25bqfAykfPM=,tag:OchHC6X4yeVNW3y1hyJBLQ==,type:comment]
    drop_multicast: ENC[AES256_GCM,data:qpyptw==,iv:j2K8KHTJKuPiXxiNFvD1ytZrGuv/V2TM9sLS40SIohg=,tag:Z5nV5V1+xPYA6Orn2pwPzA==,type:bool]
    #ENC[AES256_GCM,data:uHGdXo0p92m7iLoIbh7WQPhk7g==,iv:45iNDD9C24xbN7BeNPnvLYU0gb1r0lcac9jJZ+dDpvM=,tag:5uMOO4TDmeKGsnJhn5VD4A==,type:comment]
    tx_queue: ENC[AES256_GCM,data:OyVD,iv:i67Ph2vNmp6gfsuP/YOgHXNIXlptqdMbqvXi5Dbivi4=,tag:e4dt/TpYHRPGGkSfFdymBQ==,type:int]
    #ENC[AES256_GCM,data:0t4Zzrv+iMuDsf+hv1Nxait5rjc7qn3IJ3yGQ+2Bsmb4kEWCrifxEOA6zpxGclydFvZAqNf36Li3gE0=,iv:YWEuzncmfvPDn5YUUMyzKj6cGVvyPZkN7DuzfyhfD7E=,tag:vms8FhtrnE5bFumpkkTUhQ==,type:comment]
    mtu: ENC[AES256_GCM,data:4mocwA==,iv:TsFCv5qt5YH0Cj0j5zeWb+uJBbXZMkuTknIBRt2PX1w=,tag:5iXYa0FYnpVoHUJMfYE1yg==,type:int]
    use_system_route_table: ENC[AES256_GCM,data:UAoF4w==,iv:xfMHn6Myyb1BXx6BM2cZvRvsvTJ1MaU4Be2L075A5v0=,tag:MJjlaVWPmA6FlbnfIVW5Ag==,type:bool]
#ENC[AES256_GCM,data:6CDcVcYjP9hwJFzb3ZitiLEkElMl7Q==,iv:NhVQ8c8HqWPUXK10+WMcY73CUGcI0VWigHsvJrKTb80=,tag:SLw949zTKVDVIoDzT9BF7Q==,type:comment]
logging:
    level: ENC[AES256_GCM,data:8pRg3g==,iv:OoL8bKi/6b8138YVCzS3uvA0PgtzYha/V+m8Es5jF+Y=,tag:3qQ5HCgRG8H/hEybCsR1NA==,type:str]
    format: ENC[AES256_GCM,data:aerbxw==,iv:SYhWfnO1eRJxMLCTp1sHzohvqX3qoEZD1Z94kZ4yso0=,tag:3reY+eqNlGLz2itiyOrufw==,type:str]
#ENC[AES256_GCM,data:zCk374fRYvoiM7mIKsEPX7ILyxNpjguVyUaHmzZ4oYYjo6v9fBDaz2VwJ8Gu6BaThmbg8Y9b5Zyfckyp8v2aeWbPW7fzmg==,iv:QfmZ8+r1HPiQH6zuELXyjPkPJsJ9KTzD5TOyku56hsA=,tag:zjaU1ucMC+/tMIi+T8EmvQ==,type:comment]
firewall:
    outbound:
        - port: ENC[AES256_GCM,data:t+FL,iv:RcCmAY1GlwnJsH+yO7ZKw0xJd7J/6LIf4pSdKYKc4CE=,tag:jzvW3ex49PIP0VYux3V2Aw==,type:str]
          proto: ENC[AES256_GCM,data:/V+p,iv:WUbfO1Fkn1mNQvL6I+3SgY4bWEM9QpNDbtLASJ/D9+U=,tag:wRHze21IFT4DGBkRbbCzSA==,type:str]
          host: ENC[AES256_GCM,data:bpcu,iv:6cSctg8b1pVvHIRwpgw5Rruycod9QpyU4A87uOWpe8Q=,tag:0Zso16R5cw4gZ4IXr0u4rQ==,type:str]
    inbound:
        - port: ENC[AES256_GCM,data:/gpk,iv:3ttaunatqAnIUpRLf1MRiVogyDb/s0r2M1VMO/yY2SM=,tag:ceq4mPyzBSDfC6OUlwsgTg==,type:str]
          proto: ENC[AES256_GCM,data:PTqc,iv:4O6PJoR6G97nyffBptFpndxI+Mpb/mioZMBuXz5UdY8=,tag:ZXb4g6rBHtLrSJ6wMuLO8w==,type:str]
          host: ENC[AES256_GCM,data:eLfT,iv:VrOzQWEWgf9as6c1D9R8H78wydYCqDLuvROMwvpC64Y=,tag:H6LK50Gcav37JAmWwXAtmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByU3JVQWptSHRuWVB4Wlg1
            OTVoa2EzT1RVdGx0aGtKekIyN2VGYVg4bFQwCjJ1c21VSE15R2RsbXhyeisralBF
            Qm1rTklyeWNTYzhvYTRCNnIxMVVTSXcKLS0tIHI3REk4ODUzaFkwT2dZeTY3Um15
            Z3VkOUVzVmlYTnQ3RXVJbHhtRUZ1NzAKfUum7Wn6TkeP7vAKVAj5xpF1psDCa9AV
            O9hGSiUDs/bQXznUWVqgd6O5n7T1yrXL6MzKvokyxDZrfv7k/Lz71g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-29T16:26:23Z"
    mac: ENC[AES256_GCM,data:OAEyTtJ5X823Knbz2YmGp1DnvWvKXYt3LEQ2319TM76sO4NrMHnQhBe+MHW0y0lPlaxZsDgwcyulkutiPpdzTByXQ5BidOYqBEfBep/9i+YiAnCCV4MpWkshP7VYM/glZw+QmmGrp/z25l6cITWJzGu/j4Z+Y5gCNbOdyZbfQGA=,iv:A5saMlAWVOodl8Qsy6BPPQdhJdLLZwPSCxUfCcKGMsM=,tag:AID0JK1REJt3i4MYDCH9Hg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
