acme:
    domains:
        - ENC[AES256_GCM,data:Z1GMN0kcWR46AlORxA/nXOY=,iv:8bDYT2EWyBxQ8JCDF2DPz+NnJ0zCaM620STreiiORrU=,tag:39QImx184np29IA75xA7Hw==,type:str]
    email: ENC[AES256_GCM,data:sujgKeDacvirdhBN6BWLwu3yEVap,iv:Ykaqr0QiBdDD8nifHVEONuFuHxXPB9ukWtrh9plOYgI=,tag:ZUM4RHmlzopPT17pIMp6FQ==,type:str]
auth:
    type: ENC[AES256_GCM,data:J+GAobnnBNo=,iv:YNQYG3jN0CzBYFKpG5+kgyoWzBuPiPlWFTBvguBHwB0=,tag:M34qZ/dHhMjxtkpEHZ3j9Q==,type:str]
    password: ENC[AES256_GCM,data:YKReB6y9526Ok4GzdTly4w==,iv:WA+fEbndNw3/KxzRgRNsfOJRshLjkPMi9WxP1EvmpKg=,tag:REhfKFGcW9q1cnANENJ6iw==,type:str]
masquerade:
    type: ENC[AES256_GCM,data:rNiQ3gw=,iv:3BdQcNrk1fi0sf1pZrO8PpEBFrcRv0grXHhurU1v7Rk=,tag:DpJodfIxVCZ07PkYM9K4rQ==,type:str]
    proxy:
        url: ENC[AES256_GCM,data:Z5ktcR8Q44ax7CRgXaPw4FQE/eo9Z/KJm1kfT7w=,iv:4XFwgu2acjyb/F+/uQLL9jA3BI4dAXxXZUcclN7kSs0=,tag:lO4l35piyG8IMQ5tAg02UA==,type:str]
        rewriteHost: ENC[AES256_GCM,data:gwQYzg==,iv:oORpA86KKqq0vbfIkr+xssTJIweLQZJ/qQC9+60E4WI=,tag:yaaHNUrqccuCdr/IuRVfLg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZms4UjIrNEthSlhRNnQy
            S09KMXIzeVR3MHBGTmg1b1U0TzlLN3JpMFFJCldxZ3FpeHBzejZpZWxyWTBxMGV4
            UUpKbW9EclJqOGVqMm03L0J4NmpPdFkKLS0tIGNSVVJJMEg0bmZxQlMzaFVXRk5Y
            UXdrS1Q2aGpBSkV0dGMvaFBWSVpobUkKucE/gJFcIFI/8bDZp3Sik9Go/yz1Ux3M
            ciAGcDaEIKmTtuKRdOsDceBhSntk7JM9YaYEx1DzJp06vD40swP+Tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1efdgqxst6zk3vysvnmrexuh9csqwz9nwhtr9uyp77xn8epddvcuskq8y9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ2JXcXAxOU5FSjlEdlRI
            U0hKdWdOZXlMK0lRMnh4Z0t2NGs3aG9lSm5NCnB4bStXK2ZBbUdyVkxvT013T21F
            Slpvb3ppVUdhbC9GNm1UY3BwYjRqTU0KLS0tIGtWVkRuS0xLcEw1cldQVndkbEM2
            aWE4bFdhc3NBV3lGcUZNOG82UG0zUTgK//xAI+5i07iD+aRnDcnxjrHgNnzCvGF6
            ti+VJN8nhMcRnEpZVwwMHVnpzePd06f6SZH5o+4zCRp14hgTV+RF+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-25T07:53:44Z"
    mac: ENC[AES256_GCM,data:NI8WyKf3yCFwvMlmZU7lzjBD6EWRielmkpmsmO0sVPIj+LJlWZ9RlvuUcG2/ugc2rU1AEM3s1oLMXe6r3TjNam2RXhg8dAmwGaLki8os4o0/7OhZcjMMRtakYscNfbsnpI7pmwz0eWp/EoVNK4xzzozLdd/fcgPTExfnbhdYgi4=,iv:W7xQuZO3a6caPgC5YqID73ntMXFgDvG/IoqT6L+JCIk=,tag:K1NX58VPcAhtDpG4zKu+dw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
