listen: ENC[AES256_GCM,data:0NC60sA=,iv:+O0Dq7viJCFP7eD51JPRIiwLBElXijc3zXpetL8yBpY=,tag:SDl47gAozRlYsdvHx4E8Og==,type:str]
tls:
    cert: ENC[AES256_GCM,data:PGGbLtbLpkzi3yfRvbPPRfJuAf1EGlKXVQGeKkHONzSiCK0=,iv:v7OZUP9fFN9qnKLV221qmnm8QmPL/P4MgYkoxyUWEww=,tag:EV3X7HEfEGp++/8jPdfJow==,type:str]
    key: ENC[AES256_GCM,data:Tt+kt4hv8GPImydgKaKpzq32CwpO3+gy9K5HtCkBOwxwaAA=,iv:3iQMpdK0sa86DlPrL+peV3O5ZV+1TNxGxCqdKBYAFgg=,tag:mkqKY4LPh6OiKUFP+E53lQ==,type:str]
auth:
    type: ENC[AES256_GCM,data:J+GAobnnBNo=,iv:YNQYG3jN0CzBYFKpG5+kgyoWzBuPiPlWFTBvguBHwB0=,tag:M34qZ/dHhMjxtkpEHZ3j9Q==,type:str]
    password: ENC[AES256_GCM,data:YKReB6y9526Ok4GzdTly4w==,iv:WA+fEbndNw3/KxzRgRNsfOJRshLjkPMi9WxP1EvmpKg=,tag:REhfKFGcW9q1cnANENJ6iw==,type:str]
masquerade:
    type: ENC[AES256_GCM,data:rNiQ3gw=,iv:3BdQcNrk1fi0sf1pZrO8PpEBFrcRv0grXHhurU1v7Rk=,tag:DpJodfIxVCZ07PkYM9K4rQ==,type:str]
    file:
        dir: ENC[AES256_GCM,data:K7PwzoRugE8m,iv:333H+oxat4m/22KFqkAat7WJcDMsNB4N4WU3NWJyZdU=,tag:QdQNfRwzZGCLFsGOF0QSOQ==,type:str]
    proxy:
        url: ENC[AES256_GCM,data:Z5ktcR8Q44ax7CRgXaPw4FQE/eo9Z/KJm1kfT7w=,iv:4XFwgu2acjyb/F+/uQLL9jA3BI4dAXxXZUcclN7kSs0=,tag:lO4l35piyG8IMQ5tAg02UA==,type:str]
        rewriteHost: ENC[AES256_GCM,data:gwQYzg==,iv:oORpA86KKqq0vbfIkr+xssTJIweLQZJ/qQC9+60E4WI=,tag:yaaHNUrqccuCdr/IuRVfLg==,type:bool]
    string:
        content: ENC[AES256_GCM,data:uzGl0k61VzIBJRcn1Jbx0JyD,iv:DmxC1Qd5jklpG+0FzdtU/Haqa4zDLLOkinbpRG6xUFQ=,tag:EMK9N89lOZGdKU/311Vm0w==,type:str]
        headers:
            content-type: ENC[AES256_GCM,data:MG4swz3Yph5dCg==,iv:nWq/JBZhdeUdR9QEVnprvjdvR5o6132xRkAYdkF2nSc=,tag:4b7oc5XIE8jdhTkF1njgHg==,type:str]
            custom-stuff: ENC[AES256_GCM,data:6yKeO+eWy/quf3KRoHkIfnE=,iv:PN8l40ho4lQyC0goQfPMta6gGvbJpwFCEF68Fpuw15c=,tag:YhIEtL02I5VwrINoDwlRFQ==,type:str]
        statusCode: ENC[AES256_GCM,data:XOJd,iv:5m40J1nA28i37l70jtoUT9PjJgvlambjqz2bPOnsQzs=,tag:PWcVwHzraSrE+mkyR8cKeg==,type:int]
bandwidth:
    up: ENC[AES256_GCM,data:9CgGbtOw1w==,iv:ROc8fHdMBVoToXDS5QiVyw61RuBLhftpTZkDeX6wlio=,tag:XAmWSul6mn3R+lfMypGcwA==,type:str]
    down: ENC[AES256_GCM,data:UWr9Jbp5tg==,iv:c/hL37PnDUMLXYsSZvjgSRFWhgGRH/75ATxX3gjCEuk=,tag:wWzKppMzeEONShOtWy5Anw==,type:str]
udpIdleTimeout: ENC[AES256_GCM,data:56Rz,iv:ONELgTw3qRLK7TA/x1JIME4ZMuebBzXfx2cfV5x0Xls=,tag:Ze0iwu1P+LYR48pAkaK7dA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZms4UjIrNEthSlhRNnQy
            S09KMXIzeVR3MHBGTmg1b1U0TzlLN3JpMFFJCldxZ3FpeHBzejZpZWxyWTBxMGV4
            UUpKbW9EclJqOGVqMm03L0J4NmpPdFkKLS0tIGNSVVJJMEg0bmZxQlMzaFVXRk5Y
            UXdrS1Q2aGpBSkV0dGMvaFBWSVpobUkKucE/gJFcIFI/8bDZp3Sik9Go/yz1Ux3M
            ciAGcDaEIKmTtuKRdOsDceBhSntk7JM9YaYEx1DzJp06vD40swP+Tg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1efdgqxst6zk3vysvnmrexuh9csqwz9nwhtr9uyp77xn8epddvcuskq8y9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ2JXcXAxOU5FSjlEdlRI
            U0hKdWdOZXlMK0lRMnh4Z0t2NGs3aG9lSm5NCnB4bStXK2ZBbUdyVkxvT013T21F
            Slpvb3ppVUdhbC9GNm1UY3BwYjRqTU0KLS0tIGtWVkRuS0xLcEw1cldQVndkbEM2
            aWE4bFdhc3NBV3lGcUZNOG82UG0zUTgK//xAI+5i07iD+aRnDcnxjrHgNnzCvGF6
            ti+VJN8nhMcRnEpZVwwMHVnpzePd06f6SZH5o+4zCRp14hgTV+RF+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-27T11:51:57Z"
    mac: ENC[AES256_GCM,data:c0KjIydvKL/SANtpw7M39puQO48YdPQe8AuiuD5ZWbiBlpxzgNfYP3sX3327TE6tNLPw3w2Tkap0PawRwFiyuvIBnzNQ9tasUmSIVSIjiyysUW2cU2bnABdoIHuQ+mmjUqAis6sOIMvWx4cSvGKYeuk87KL6bzWgIsujxnxquF0=,iv:MWOLVwE/kyZw9BqSeFU4AHEkZ2qsCRqgBeSI0S/6wfE=,tag:MN/KZjt7e0YSby9r2VepGw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
