{
	"data": "ENC[AES256_GCM,data:eq2VRPP+vanHp6bV4XBmbkpSYyLIeDZuEPKWUy/Vu0JXZzBwli5MCg3awv9GenWWXo6BbQwXyw8APctcQ/ERgQgv6TvhG8PC01eZPhKNnEvis5kOKTN+XaC26xEmvGNzq5AkIu3ssEVRwzqMStn/RY8oNLr+NPfkeLp7Ck9diLjjLVRJKE3D4YT0VKTwGUJmQFm1y1lNPv0tLWeRuvVstLCjtb8/OqT/R/YB9jmQDqmZptED2+O64xVjuqt+1ra9+9tW/uV//h6RnPVHY/fDMJR1e7DWEksDlRWwP8Drfn1Y2cZuLhuLhoKJToStafm6ENUEvTQFZvwp8gkoJ8AIYMy2xJSZdv0vAudL38fj9sUCXlaImb7FmFgvE1UwMTXy0jToPFB9il+2oD32vbqdNs2H4QRUK5FjttH0GnVf4fu3OiuKmreB3PUNphILxIAFWG2mn02mTejw44sXbyePdZn//0Yj4ezRDZxJpbXa/No69SY/28DAyhZ7RppC8xCRywzde6mKom+bSWLzE9h9TQ8aHYn03Hhmew8Vtbm5KbFMOP9c0wA+FhgmJslSxYsnlYl+xn2ijn6MxvSDD9PW5M+Ffx9m0FIx9MPkCFtdMVBMbPbWNRvbsZNELMVu7dBezApIDti/otKxa7FlFoBUD2errpXSl//zftxzcSLVWFM99fLeSnBME54Tt96ok8K1OP+ihfU7IGln3TEQ6tKnYFVv5Ny4Wp9B9wpm,iv:GJkVmN1GHCw1i+tgIDbldLweXXubDHStgl/1lgxo1wk=,tag:jjuZyulHDdkPAIqryOXs3A==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWa3hLSmVWbU1XUTJ5TWNW\ncGhxWlVqdUdGRlZLSXBNZndOc3dudjhYdWpvCmw0ODBiRDF3L3NlS1BDeEZjQW1v\nMGVFQTROS3hRSlV6SnNIeXpCa1pUcVUKLS0tIEdpWXF6cVI1a0NmaDJTdjFVWTdT\nM0NWM1hNWk85ZmNrbElqREIrWG80ZlkK8Tck79VjeU32FUkoTKAD8xt4/m1c8Kcg\nQLO7qbEkv63GkZCfUtTxeYS4fs62opAY4iaFpb+2zHUit6vyR84bRw==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1efdgqxst6zk3vysvnmrexuh9csqwz9nwhtr9uyp77xn8epddvcuskq8y9v",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdys1YnJ3cURKb2x0Unh0\nZkp1S2VuQk9vQWRXcWlUSng5bWRhNVdpR0VRCnZFZmwrKzFUb1ZMWENtMWJUMTR6\nTFFHRU9MUVg2TXlUZmJLWVM3M1dzQncKLS0tIENxbUphUFp3b0dCakFRTjEzUTFT\nMSsyOHRscGlQOURKdjNqbjFaQUZaRGcKbFlOfgZgGDDp8jw/9wS34jMvvl9lqAz4\ncqa2I02Qo4LJ3CFKFMj8GByMEX7qcEXzLj/laaNiT1YVt9ei+VhSfQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-04-14T14:29:42Z",
		"mac": "ENC[AES256_GCM,data:1R9K2zdbbbegcTUFxx2EbMcwoZlx83aO/+Ch4RmcMw63p9vgDSf2St0H3V8a2r2gAvhtvbEhMr3tP2yL6lTpUdwV2sqNmfLuBmYC/5Q+m1xTUBHqcfw9FYGMyyD8HtMr9Qgz1SebE7QSQlRy0VlaurYj5/95B/W+gETHoP8bIKs=,iv:K44N370kfgKmgN26fep2pgk+GIHhZN1VC8NtxBP48Gc=,tag:n0B3pEB7aToKgIxX25kFdg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}