{
	"data": "ENC[AES256_GCM,data:WWjbp1DOjlUJ8IZKJtEucOpY7YfLXgUWbW9Ytzw2RB+NBGunqpFzO66aAB3Z5fzRyfI0XOJCli30PQpD08Jmn5NAA12+OX/4rl1N4XnXzD84KiKPB8nbMW8cgBplan6U/bJmQKdiSR8ngoHEV1TlrlMr6bYbGCYepznPol7bPwiCaRpA5uyOqR8jMQvcQ3aWqKOxVkYaM8iIUwAahHXTKAvALojjnD4zBj0eHhzK,iv:0CkSSyDTxEprZ54oxov8ulvarJB0Csyc6fGOI7Y+QZQ=,tag:dYDWs55E24p5Am30p5aHRA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SnhrMTRMSUlZTlI2Szhn\nRWcyMUt4Mk1Wb1lmM2R0MnJnQkdHaHFSVEFnCnk2NlZ1MFZCWko3NkVkTGVjNnJq\nYkEzcXFBTXpkZHFYYTliVHQzUnRiaEUKLS0tIE5IQ2s4OEd6enR6eTRJbTBXRVZt\nQzJtZWloam45TU1IQmpod2FzRnpqM1UKDS0U3visTYywPE2qutP+3DdLk3khFM1J\ny5E5+TuVfTPXwgyvXiOrcgoVfCcgZkwvyRVq6uwuixgj4SGq1rHdjg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1efdgqxst6zk3vysvnmrexuh9csqwz9nwhtr9uyp77xn8epddvcuskq8y9v",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM29MdFpUS09uS0l1V2Y1\nRDNVVHJ5UXJIRTBsVDVSRlFhcTlKMDdYblZnCnFIdy9WR0J6Uk80L2k2THltKzFW\nWWVsbGRaeFVYRk9XcHB0QVJybmNBYTgKLS0tIHExUXFSSUljdENTY0UxVzNlbFp2\nV1lLSXhoaDQyMXBQZkgrOGVid2RybDgKWrgNZN2rGQOOr6R8wHht/WWrxCQJti0s\nnZqipI27IVUkhZv27/yq7UfDuUanVZPvPVrQmBhCr1Lg8Qx/Irv99Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-04-15T03:26:08Z",
		"mac": "ENC[AES256_GCM,data:Hy9OeJkb3Fr8N+ttt33ACHlHCS29/On24lEpZ18uNG/0B5WmOKnWYQ5R51TkobwlG7uSYXbM+Tro0hcD9WrAedCiXuOY6yMgWZvLCh+2KAVfJnSWb+SZrPzYXWVBG/mR9GKttFpnb/Z/H1sVnv+joik9Xg/34HHWeWdRcAhvAcs=,iv:x9fUnBJrA9tn0fpNHI714Dm+kRWxHslcUSHDYX6yn78=,tag:rLJcNl72igPUhdaDmMWWHg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}