{
	"data": "ENC[AES256_GCM,data:FPiLACTC5Ly97tvHybhQvJLN3PG6vd6cP9eiKQo5eNUnzWe2,iv:7iJPuA+ZdjAQCu8B8gTN23X1CTvJjOqLyaMzKf628ko=,tag:7J8Vo+/MVdaGk/64Q60sgA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SnhrMTRMSUlZTlI2Szhn\nRWcyMUt4Mk1Wb1lmM2R0MnJnQkdHaHFSVEFnCnk2NlZ1MFZCWko3NkVkTGVjNnJq\nYkEzcXFBTXpkZHFYYTliVHQzUnRiaEUKLS0tIE5IQ2s4OEd6enR6eTRJbTBXRVZt\nQzJtZWloam45TU1IQmpod2FzRnpqM1UKDS0U3visTYywPE2qutP+3DdLk3khFM1J\ny5E5+TuVfTPXwgyvXiOrcgoVfCcgZkwvyRVq6uwuixgj4SGq1rHdjg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1efdgqxst6zk3vysvnmrexuh9csqwz9nwhtr9uyp77xn8epddvcuskq8y9v",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM29MdFpUS09uS0l1V2Y1\nRDNVVHJ5UXJIRTBsVDVSRlFhcTlKMDdYblZnCnFIdy9WR0J6Uk80L2k2THltKzFW\nWWVsbGRaeFVYRk9XcHB0QVJybmNBYTgKLS0tIHExUXFSSUljdENTY0UxVzNlbFp2\nV1lLSXhoaDQyMXBQZkgrOGVid2RybDgKWrgNZN2rGQOOr6R8wHht/WWrxCQJti0s\nnZqipI27IVUkhZv27/yq7UfDuUanVZPvPVrQmBhCr1Lg8Qx/Irv99Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-04-14T12:39:27Z",
		"mac": "ENC[AES256_GCM,data:hHrzfU/Q8wqDONV2pXtPiTKAa+DhEjEtCue2+ZNlGYa5SFIlucXx5KWmIMZslVZNgAyDpOcHcKUpfDSpKMSBqQqtVsWDHd61N+vwTPLZRy77G0MDlY7Pu+USWDOftxe1uVygkfsFDGm2WRp1JS7l47RjEbrJ5+W5SltlffNRsd4=,iv:IEnnyDsWvRHpxoOBGF1VJ1vCd4EMMxEximTiY7G5GDQ=,tag:vtL+mQiTmDjgq75PY8IZzg==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}