{
	"data": "ENC[AES256_GCM,data:R81rhHdp81ORTuJbdKhjYdAjyyn2PKAz+xMeOL677cZKuQFTKxhdHoaVd1B17IEAeJxAnY1qmGNJaPiVS8HEgUIUnDky6X1ljSgwa8UkBGt0yMmMwMl/wlpkD+Cwk3VLxSab50i0onA+uOLwBM1228xaQSehcidmTsoQvodnpvcqeTLN0kC7dTqjTCoGotnpx+ZxL8dDZM2UDA==,iv:Jfq2r4TPj/E+YTstw8JGvjJMT2HoHcB4gy3JQgreUG8=,tag:KMXxlsapExTdkNKW52tYiQ==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SnhrMTRMSUlZTlI2Szhn\nRWcyMUt4Mk1Wb1lmM2R0MnJnQkdHaHFSVEFnCnk2NlZ1MFZCWko3NkVkTGVjNnJq\nYkEzcXFBTXpkZHFYYTliVHQzUnRiaEUKLS0tIE5IQ2s4OEd6enR6eTRJbTBXRVZt\nQzJtZWloam45TU1IQmpod2FzRnpqM1UKDS0U3visTYywPE2qutP+3DdLk3khFM1J\ny5E5+TuVfTPXwgyvXiOrcgoVfCcgZkwvyRVq6uwuixgj4SGq1rHdjg==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age1efdgqxst6zk3vysvnmrexuh9csqwz9nwhtr9uyp77xn8epddvcuskq8y9v",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM29MdFpUS09uS0l1V2Y1\nRDNVVHJ5UXJIRTBsVDVSRlFhcTlKMDdYblZnCnFIdy9WR0J6Uk80L2k2THltKzFW\nWWVsbGRaeFVYRk9XcHB0QVJybmNBYTgKLS0tIHExUXFSSUljdENTY0UxVzNlbFp2\nV1lLSXhoaDQyMXBQZkgrOGVid2RybDgKWrgNZN2rGQOOr6R8wHht/WWrxCQJti0s\nnZqipI27IVUkhZv27/yq7UfDuUanVZPvPVrQmBhCr1Lg8Qx/Irv99Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2025-04-14T14:34:03Z",
		"mac": "ENC[AES256_GCM,data:TsbP1wFotN7O96aMrhy9xcqvvrsrofkOYDI0LiolJ4p70OsvLRM3VVWMokjCOjeAINb9l8+/Xlv8ROKrSvLz5uwdjlC0BZ9hWc/Xy+lGl0dW5Fbv4C6jjK5uVLBOL0OYUIYNDTsmg499z4fdcBRTt9mhEypewHZNJ2GoKthSaqQ=,iv:YZv5YiNQc1GpIJ2IZeQoXrNb8PXrZY6iqIVv4aIlALs=,tag:wN7haAhJ5Cve3XOxePLkjA==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.8.1"
	}
}