log-level: ENC[AES256_GCM,data:unTe84w=,iv:Ptz7QgyYGvHIYYn9fl2oObtenbEfDJrHqo6gbq2xr88=,tag:RJDMeoKzAXSzurgYbcRykw==,type:str]
bind-address: ENC[AES256_GCM,data:5A==,iv:oTVqDEqriwcszhX4ZpwvxxKfE47MErtsPC6EQwtQlhA=,tag:o3/sX+EH9F0ie5vd8dKqAw==,type:str]
allow-lan: ENC[AES256_GCM,data:aGBIx9w=,iv:Gnu5BRFg2thMS6XoOXxNPTkO+jZe4u7UGXCwqYzitrk=,tag:fAuoUWZyn/aisR5pye25TA==,type:bool]
mode: ENC[AES256_GCM,data:rz/iSg==,iv:SuTie3o6eL2GDMSB/cwU/IM0c5cSUsIJPZuaipXp3jI=,tag:xrOjnLNGVqSnR2FuOUQOGA==,type:str]
ipv6: ENC[AES256_GCM,data:llecWS8=,iv:1sQXcB/P0BKGSDQY0FUHmbhZ3WtD4KR74cFFdH5uhSI=,tag:08+69YfbNBpVZfNFMhs/NA==,type:bool]
mixed-port: ENC[AES256_GCM,data:2Shc3A==,iv:zSjwyKfr+27wbUKW/4HPx1D+V+mmJqABsIRYp81b/9A=,tag:gb6qB3TDR9hz4aKa4RQ+JA==,type:int]
tcp-concurrent: ENC[AES256_GCM,data:D7G+7Q==,iv:zKbi5Jp689+ycumCqzEtSG+SFIjXrbCxacAR88fObCY=,tag:vURtd4rsbE+ZFAbTIlTPhA==,type:bool]
external-controller: ENC[AES256_GCM,data:ZPl7ywkvRcl9ZTSD,iv:F+mUMFxt3tHeQ22wsMMnhRwH6+lyWb/JKmiM3VMyyuE=,tag:f7DKyXqzzSjibeoWnon+jA==,type:str]
external-ui: ENC[AES256_GCM,data:4eY=,iv:nvrPGfk048Xh3FR9oZcUNK3H/BMuw7NmjLc2+5v3Shw=,tag:qP6KlNjzMbTfabfbHlQQGQ==,type:str]
external-ui-url: ENC[AES256_GCM,data:FZHlhclXtzNWochtxMsjMGA4rWZjJMLL7x41vbYxiWy9Y5yWCSp95fBSXYC/3roiYd9Sklo6fc6a4OL9TM+1hDikgfhUhpU=,iv:+uQOGyPeSeyfi0tKWFh2/OpgjYCdAkfYRBgBXyE5dVY=,tag:1T1bdS3ynGx+jbWFmW+T+g==,type:str]
#ENC[AES256_GCM,data:zRC90phFRg6o5qOXlnpwz9jQtmzcb+l9MuEjC2cXpd33dPw8JkWm1RoaSwpNnABkPycPRwSXJZsAVSF2ej7DKw+D2KSd9hoATyDaD1wLQg6I/Q==,iv:O4aP6BydbWg8D/RHYVvtfYqNE7WtKgL33U2AQwJiFlA=,tag:+2gVYFotvrty0tV6kTjExw==,type:comment]
secret: ENC[AES256_GCM,data:N90BGxWHfC/l2pjs,iv:xEda70FjT0Y8fVf0FO0N+jvh/SHERkwti4N5sHPNIIA=,tag:dgUNLnJTTCHregRRRUMAfg==,type:str]
#ENC[AES256_GCM,data:0o2Zmjqbr57LEk5/RMqQ6Nz9RhxXUkbhJgByFnYl21pUuvAINqo7KsU3lO19iOsRz0p36/xN0pNPNP8f69ZtD1Y=,iv:+BfQi9nrowNiAEwTPCI8WtTsiSF8nmO2jPYTJu9uGcA=,tag:WvygbVcUGV/1PLAgs5s9iw==,type:comment]
find-process-mode: ENC[AES256_GCM,data:WJtt9YMl,iv:eH5KGKU9J4djhJ9v+s18onEkvKLc6cY7mQTdBeNvc5E=,tag:/TOewYcxGIq2gdS/Oiw5eQ==,type:str]
geox-url:
    geoip: ENC[AES256_GCM,data:Rrk9t3KJPlAXThbkf+zZBUoZwh81mhu6AA5Rj3tK697OY5dxaDjSyTMH4VDYa08CgYfV5GnHavXuZUyyNu6TGhM+6jmiUbmtDHw/EA==,iv:FbMbURVN1rKWSqxKsuhBGuYR1akGfSfW7VwoIHJ8nU8=,tag:SKoJEah6fHjqvja82XlVZg==,type:str]
    geosite: ENC[AES256_GCM,data:tlvo0bKocVKFvFQd/F7IGdGkrRhnD7Qd5KZm822pAuqLUSZuf8DLaca+w7CeREQVCQyRhySDcwMvBlRmTpW5V1mYt9pmFJuu55wZUjBJ,iv:rDVJSchwEh6tG28WYJgo6LpNAK6Kfx/pG4uXai7Mh3w=,tag:ny4ZY5sqtYAnglcLHn3sjg==,type:str]
    mmdb: ENC[AES256_GCM,data:6NgI4sVpWyBqH2+vifUCFbpqRy+EFo/j7cRiZWFjlV7+xWjh5SbpteLiteY5XaHTlnrohSpuKU4unv5zbwTiNFdZdlmgxTe5WvfuzJDdEA==,iv:8Hg4eHgs+pzCL35qZCFwyp2bigj6Hh3ZCJ9PVXC48xw=,tag:4ap8LX41elylhVchBZOdFQ==,type:str]
    asn: ENC[AES256_GCM,data:uxWlTOPxFDsLAtrnGYaMhI1X0GYQuTNGwNIj9w3/l0iHlfZWQ0YJ8mJOVUOaXZkMmhZ9VO2BNU3jGusJuQrrB/B9ru9m4xWy472Pq41CXA==,iv:jZf+1X4eueoH0VyRU6iBTMY3J/UGjsGojW5P53s4ifM=,tag:aRlkaIu+tEpgZICn/n1G6A==,type:str]
dns:
    enable: ENC[AES256_GCM,data:IBDmkg==,iv:qdOwxW0RXfqbjYAE4AHkdw3MxyLmVAGFJI9P7+r6Drg=,tag:WNEf7ygkDCva1qYh9wiLHw==,type:bool]
    #ENC[AES256_GCM,data:Kxlyzxk3YYdbyBeNwqI=,iv:sJ+IEOnuWMq2Ni3qdeJRLZpDEiSt22G9mG0rb0CI5V8=,tag:Gi7gXeFQNiktuY891Zp6Fg==,type:comment]
    ipv6: ENC[AES256_GCM,data:BWAmi7M=,iv:SCZWcmFzm7OjM72Vi79FzycIDZgwb0jjoi7xNqGqY90=,tag:oSB4bc8TzcVdYy5Rg8cu2Q==,type:bool]
    enhanced-mode: ENC[AES256_GCM,data:DHdPLHkwnw==,iv:zBbMo21Sfwt0HEyrzLizqAz8BEcbar25sR6NREHVN6I=,tag:EvNpTIid4f4DnXJSgY/Qmw==,type:str]
    fake-ip-filter:
        - ENC[AES256_GCM,data:xw==,iv:mIRzPRw2NdDA7aZu3M2CwVTzY+rgsW5GbR7meVd0h1U=,tag:RjrBjeSnK4qILbwxXiVyQw==,type:str]
        - ENC[AES256_GCM,data:HZ+CdkA=,iv:I005Pv/lACtSqwUApfPG4D9ny0fg4usB+9KVphRO+6Y=,tag:jLXVHdrQ7q8gTW+yrn7IkA==,type:str]
        - ENC[AES256_GCM,data:4XIQw3Ixbw==,iv:m0Cy8xv6kXGPkqnFgythkqmQA28bg7kn3jvZ1rDG0Y0=,tag:Q4KL2r0W8hlHFowi6l6Zag==,type:str]
    nameserver:
        - ENC[AES256_GCM,data:PStM6HEXGO3PwINxuJSLKjnG38jLcNXenQ==,iv:EU1w02Phcooj0hFZAyxpDbk+HRujGGyIA5Vr5bczosc=,tag:X5GgAFM9O59DkQhRDVMFTg==,type:str]
        - ENC[AES256_GCM,data:cIU4ZHENcHGlCG5U8ptTsWRlZTOCugeG3cGBdx1c19c=,iv:9JEHm54lk1DMIwF68kn4c56RPhWVAcFjVukyjTNbMUs=,tag:kleETYeY2FmVt2MirLz99A==,type:str]
    proxy-server-nameserver:
        - ENC[AES256_GCM,data:AmSA45NnzqYRI/MjXxbU8eM2TPmjIy/mJA==,iv:qE/KakElCY874vR9RvPTykwJt0zFVrwj3FPV0bXU44k=,tag:+HOqc0RPwNb7glj39hz2lQ==,type:str]
    fallback:
        - ENC[AES256_GCM,data:t8psHy6trVQvWqyts19myuWuZrfY+IFjLg==,iv:GOLrekfr4yHg+sr7WxIJGSQBz4dzelGbb4LIigkgSn4=,tag:TTsg4BwsPbDP02PL7RxNFg==,type:str]
    nameserver-policy:
        geosite:cn,private:
            - ENC[AES256_GCM,data:WNPzQPTZHjwml+kIs6Wn7DdschDekes6LQ==,iv:LSGwW1f4QJkLlgF4SblmWmbRvqMe7Gdp9zskfI8uLh8=,tag:S5DrSRZKegEZ2JLBqE+FYQ==,type:str]
            - ENC[AES256_GCM,data:EN2SGx66jLSqWSegLm/uPrbaY0GmkpvWcliCbnb0cj4=,iv:9p+zx3KmXX3XFl4xTJorOO475NO5gI/nkVqudjSsqLY=,tag:3hqve/CHur72Y8lY/zAhCw==,type:str]
        geosite:geolocation-!cn:
            - ENC[AES256_GCM,data:1hXZNIhr2XMOPqpKvWc1bCjI69WPW3LqyD91g46iuWSaL1RMD/9iDA==,iv:mYONIfsFtFhM1Viz1SMEGVRYxU4Tkec1QxuWFkZ17ME=,tag:CBWVE/Bgu8PMrR2GluUjog==,type:str]
            - ENC[AES256_GCM,data:EHUbBQeUSKy8HqwsyOh1TwO4uagZ1hiRacwONRFdO14=,iv:8VqjaYTuzvGbqXp6sxbRxSuI5OaYZpnMje+gbLzJYUY=,tag:inbCrVivQbB9tHPxJ+D9OA==,type:str]
proxies:
    - name: ENC[AES256_GCM,data:law=,iv:QmIUkQ3/32hbI30lrimWeujKHfAJ/5pUFJYWJafKxlM=,tag:/cx32S127XDaxfSmsigC3A==,type:str]
      type: ENC[AES256_GCM,data:2oQ=,iv:naW6n9Apl3do6nntRCpqQvUFEJdCbTsyvpiiQF/CvxY=,tag:gdwVos/Tq7SRJwLqnyNEYg==,type:str]
      server: ENC[AES256_GCM,data:m/R/p0Qk1o4HUnIJTqU=,iv:jlffwrvL961/Sx+DH+FWWDuW08ldFgCKC7Szas1ySFs=,tag:iCGonkaPvLfxrXkcySanOQ==,type:str]
      port: ENC[AES256_GCM,data:9XAXzWM=,iv:A4KMcoD0jHgeOQyRSIiQJyqi0/G551YpM6zoDVKvvbo=,tag:a3evXgk3QRl9kF12sqa1pA==,type:int]
      cipher: ENC[AES256_GCM,data:EsCrmRC0+fxkkrpgOl2fnMLzNT77OA==,iv:h1rafQXaAe/i+/KG8wRT6n/ck4UsThgQBxqVTWirlMY=,tag:zfYOb2D5PIJsWCL/D+87nA==,type:str]
      password: ENC[AES256_GCM,data:URbMrLFSUd9L/QWzLpyEcg==,iv:I3T9gWvLFnpN0KTahMnR6rmkHlsmsE0WdaVXWJ5jASY=,tag:7SixykBWdwYdSc5xv/qLJQ==,type:str]
    - name: ENC[AES256_GCM,data:x70KTcgy,iv:P9wfJHNIN27/yeT6/WbtNatK2zoZKSSzCaDiWOGhnJA=,tag:n/ku2on3xRQM1gKJjbY9TA==,type:str]
      type: ENC[AES256_GCM,data:2EjNr7CZ6Z08,iv:XGZWfxQWTjBsu6DJimMECR1Z1+o82IHaBSs/gk0PrTA=,tag:bAoNKZTFtvYcigcPDVJtDA==,type:str]
      server: ENC[AES256_GCM,data:m/R/p0Qk1o4HUnIJTqU=,iv:jlffwrvL961/Sx+DH+FWWDuW08ldFgCKC7Szas1ySFs=,tag:iCGonkaPvLfxrXkcySanOQ==,type:str]
      port: ENC[AES256_GCM,data:Cllwug==,iv:5SZ84zTFzUxNna8A9B9qjeUK6mF5R6nhW+HINwONhXU=,tag:YBYFHrq0goqXOzkrAItyCg==,type:int]
      password: ENC[AES256_GCM,data:URbMrLFSUd9L/QWzLpyEcg==,iv:I3T9gWvLFnpN0KTahMnR6rmkHlsmsE0WdaVXWJ5jASY=,tag:7SixykBWdwYdSc5xv/qLJQ==,type:str]
      sni: ENC[AES256_GCM,data:LRQ6sIqOhWQ=,iv:OXRTs2lUtHe6HPm8KrUi4ywwiqqGMCaAqCsJa3SIF64=,tag:z48S/PXq/mJrWZCv8i4WpQ==,type:str]
      skip-cert-verify: ENC[AES256_GCM,data:9ZOgOQ==,iv:6wSDjUUnsF475EtTjRez473/uekAYNWU9c+7TzJBClY=,tag:w0CgLwWBPCulwgH0MDFLxQ==,type:bool]
proxy-groups:
    - name: ENC[AES256_GCM,data:2qmI8WY=,iv:vJVgWlMAi5CljX2X7/0XYNAXBoRm7S0e8Dl8HruZQ9M=,tag:KhkDZoDxdPA6s34yHVIdcg==,type:str]
      type: ENC[AES256_GCM,data:frvsHD32,iv:fYRnqNo1z26eYRtUUCaRSLlQoxy296uBEsmDUYbcIjs=,tag:Q4ywatPPHVcXQpc/IH3vfg==,type:str]
      proxies:
        - ENC[AES256_GCM,data:kF3lzw==,iv:9Sq7cATjog+9jKK/zbcmFpmeBANoA1L02DpJISQGAu0=,tag:FdZPtad7QKieY48M7FLn7g==,type:str]
        - ENC[AES256_GCM,data:hUw=,iv:xMlrVQPkHfp8QPOQRnC3w8ZnEhmHhgSzfQZU+3z502o=,tag:5l8OTK+4jiDJAThO/NNAeg==,type:str]
        - ENC[AES256_GCM,data:ieAcdq4Y,iv:UlwbYXju5OhF0QU1MW5c8SPIar1zcBbdATbShsa5F1k=,tag:n0JyxN1+Ewrg2/7gTwu1sQ==,type:str]
    - name: ENC[AES256_GCM,data:0ZoF4A==,iv:ogDAQN2nCdSwXfWcNKYabqVWBby5K0x6rONYB+3gp0w=,tag:9Yxt/A4jPRWvVkZ9aQI2GQ==,type:str]
      type: ENC[AES256_GCM,data:LOkGb8hkPVM=,iv:SAMpMH02v30ZPCTbMRIQx1v4SO0UXNi/Xfa6VFJYeJ8=,tag:khaxEhCjT48mxCtmC+r9FA==,type:str]
      url: ENC[AES256_GCM,data:CR6KDrJ1TbzV2wHBFbXMpFw+KX6qkfHbXGEkBfujg7JMMCQ9,iv:0HUhvhA6mF4tmASar3vDPtv8CRVQM+zZVNE3kX6Tews=,tag:nBh6hjeIScpw947UdKcxaw==,type:str]
      interval: ENC[AES256_GCM,data:FOAnhQ==,iv:BKP5X+98xLSyx7USjBdylVZKwAFrxAAsIG4ZVfGDQEQ=,tag:ygEVyjvyS9D+67rSZUHF9g==,type:int]
      proxies:
        - ENC[AES256_GCM,data:hUw=,iv:xMlrVQPkHfp8QPOQRnC3w8ZnEhmHhgSzfQZU+3z502o=,tag:5l8OTK+4jiDJAThO/NNAeg==,type:str]
        - ENC[AES256_GCM,data:ieAcdq4Y,iv:UlwbYXju5OhF0QU1MW5c8SPIar1zcBbdATbShsa5F1k=,tag:n0JyxN1+Ewrg2/7gTwu1sQ==,type:str]
rule-providers:
    self-proxy:
        type: ENC[AES256_GCM,data:E+4QcA==,iv:IFT3ljOgVCa0F47ouJ1j5w2PedL8daX8b2wbtogC73Y=,tag:SYWNbDH5xbBkDA20r4UkaQ==,type:str]
        behavior: ENC[AES256_GCM,data:1xq0otUr,iv:+V44FBvF90IUfw7wrdGbLYPlLfzKWtvxC5b8d8grGEo=,tag:gpVm9a2dKe6hR4I3PwRyfw==,type:str]
        url: ENC[AES256_GCM,data:B9R6u42D5vPSOf8jD/TzZ+MK3hpvupGDWEvdshscWHPqQfptE8g1r4pGfsSae9D7st2f2lI=,iv:PG6MHlCDz6Gh5lZbnJP/z8BTfO8PTwAmt1DtJjd34bY=,tag:Qh0cjmrcmP/7UItRmYTO+g==,type:str]
        path: ENC[AES256_GCM,data:vfELzsCWqOpusqn/H6cNmOuA9f9iwrk4iw==,iv:Sl+OQIQAC9bJwGmlKl7zfELGz3HOZseSsKO0qgfz+rI=,tag:5YvCf9UF070O7750Be9m3g==,type:str]
        interval: ENC[AES256_GCM,data:ZhK/HC8=,iv:0/IQ8AkL+HluKJxnN8nLBOXq72UR7e28DJNhZb8eLHI=,tag:WpfsFe/iZYHpdLWNGPLD+g==,type:int]
    self-direct:
        type: ENC[AES256_GCM,data:wSyJ4Q==,iv:/l9WrA6hYTTM8GTKGDYj3WDF+wxzmNXY5cO/PQRZDuY=,tag:mfCEjcMAz7yyqFKtzg2j9g==,type:str]
        behavior: ENC[AES256_GCM,data:eQAwySEr,iv:7hnj6DCfkFDdU0olwKsDLpwoGKmPCBYHBokEOzlWK/0=,tag:eDTTq+iw1VdRfag/EfW5WQ==,type:str]
        url: ENC[AES256_GCM,data:CppFbGmGe8KUXALLOCSJIjmywfDhf0g7+ZltRXDm3I9RWgGFCR/eRqpz9bcTJx5yF2+VKrJa,iv:1C0R1HtYLLMD0ZNA3nwFLZv2vxmwnc0i3kQJ+8Wik2E=,tag:a4mV+SU119RRslaWdDRF1A==,type:str]
        path: ENC[AES256_GCM,data:2kucR/9PYm++1/5gVvCArRysEFcYMoTmUKk=,iv:hcCmh8ArkQ5XQto7hgvIhlTm7PNKwBiYwCI1oOhBJcc=,tag:vDaDe/CfUhTRZFKsAuJqJA==,type:str]
        interval: ENC[AES256_GCM,data:O7gWsFY=,iv:3p/U+dVkvZzDYSVQSe8gBN5+nGRAOWfDRTiT2cO90wo=,tag:Ytpli3ru52XoggJnfmvhVw==,type:int]
    applications:
        type: ENC[AES256_GCM,data:Yj5J0A==,iv:1JqXr/rgkgeBrIph3F5Q1ZVaAFbPeUODLeHYAvEY8JU=,tag:B6fyDVnyseDznVxqwn81QQ==,type:str]
        behavior: ENC[AES256_GCM,data:zqoZ31VQyC1N,iv:9Wun5apP59TbnawnKg58uXD6ZmLEGVWFUzAcIxl9U1w=,tag:SAVrPWPO8xWcsI5BCQ5CeA==,type:str]
        url: ENC[AES256_GCM,data:7j/5WqrPtG5ZPKKTW00u7fU7Aw8km6r2D6WzS3OGVA5WCFdrBiMPnhnD1kS43a+qZ7YHmqLtJDjl9GMrX7fO9eFTZ1bdWswe1utNtU17Xhw=,iv:nXwKXmRmL9DhDgSEumWv0huPKueLVUAPZzzc5AuchVg=,tag:atLJL6q3xAplfLVH0nZqVw==,type:str]
        path: ENC[AES256_GCM,data:5g9jZxXXXLI3qqRpEz9g2mJMWIH9rCcY62Yh,iv:l9KpD47xDz0psQPr2/hE8L0oO/awpPS29t67xL/KGMQ=,tag:ILoly+4oQEtfpa+1AOZNow==,type:str]
        interval: ENC[AES256_GCM,data:BCimi5M=,iv:xwXWrtH/aKGwMERwVqQhJxOcpg1rdQkXAfCay6jlhXg=,tag:BGokCscU41pXVKBbk5oFiw==,type:int]
    private:
        type: ENC[AES256_GCM,data:0XhGYg==,iv:6W4QUzjUHrrrecF9aSHtBsJX6kXqSRdx5ZivS0sW520=,tag:R5vA8dN9h0xehQ76SNi93Q==,type:str]
        behavior: ENC[AES256_GCM,data:5ldX9SCM,iv:jFZwz40c+V1QYNeHsTxfh/W/WaPNgJ2Oxs67Xet+X7s=,tag:F1C8CinB15QRnnCRBVNBuQ==,type:str]
        url: ENC[AES256_GCM,data:L1HP5MBOirtfP/z/qXN4IvBJNvWenACH5gEZlm0if0QHi5C8+Y6MJ2citGlR2czWCuZTD6z3gu3/QRDPN0MOb2wjI1hTi4XemgHb,iv:gW9gkR23od+21zWhAxY+l0Vmg8FgWLuqqLvZ4j1pvgg=,tag:AZAsLiNBKbN7bdYpxuspDg==,type:str]
        path: ENC[AES256_GCM,data:lc5PpjD9GRMp43mHPyUWwDAF6Xdskg==,iv:r7vSZoKxi6AI2Gdc8MXuyFladACsdz5trL+Tt3kz8lw=,tag:JwR366DYzLXFEs8dPqMLOA==,type:str]
        interval: ENC[AES256_GCM,data:/+N7neQ=,iv:onv54nHRfh/JI8lOmm5YfVFqYVUrsakpnhdNgFCffyc=,tag:1oM2RynFfNGbmOQA5cfn6A==,type:int]
    reject:
        type: ENC[AES256_GCM,data:VvmydQ==,iv:GhEvJjDzS7YV1dSwKZzAWJU9tP3wj7p/Fp6MsE6n9f4=,tag:9S4z6DBkyKSId6RKuCiYeQ==,type:str]
        behavior: ENC[AES256_GCM,data:Vtq7FYff,iv:bMok0gEKj6jDEqM1qLKEdetSFjUrJgLWwKxtXLplEmU=,tag:P/nC4t+zqvhIcbNeoReb5A==,type:str]
        url: ENC[AES256_GCM,data:2TygkSm4Dq8leEE2zd7032iOPm+Uq4mD9YhfTQEfYXDvVI4mw8Pq/P7istNoD2smbANzQXtk524r3PkiCyhWSOr0TPhmLl8Ir6c=,iv:TERI617BiwrHv+7rS3sbGUh1AQa45R08xeXa4wP8PhA=,tag:ExZAGRjgO/YV1LrgdqA3sw==,type:str]
        path: ENC[AES256_GCM,data:RxUUZ2tDHAT7/Y87Cp8d1Np36PlQ,iv:V/1xz8Fc4W9vF5bz3n4MInmPVxQ3Nh+TfAzbHvwr3BM=,tag:OrUcq6NabVcA81d0V+YGzA==,type:str]
        interval: ENC[AES256_GCM,data:7wU4APk=,iv:Zyua90K3jGtamL6Q4K33guCoiKCQobt69IDWCslkmVY=,tag:OdYoRKMi0t5cFVd6lYgcww==,type:int]
    tld-not-cn:
        type: ENC[AES256_GCM,data:xI2x8A==,iv:YFIsBwdCaO7PIOgJp4ERB/kjHBjyw5lIJsAH/ujtlM4=,tag:n1eYEGLJqQfCc15h5MxDoA==,type:str]
        behavior: ENC[AES256_GCM,data:IifN4PWF,iv:ozR7H6ZyFmuVFNXtXAU0cj08iiVHVBYA72T1ZJd9o4I=,tag:aezwvaj4GTJ98gzwXY1TFw==,type:str]
        url: ENC[AES256_GCM,data:wpeg0hblksXcEsUQP0n/Q5KEktoPFse5QI2IW5b+NnEo9PsiRcUtstj2++KIgC9tDZzMBKRRasnsbAUFulvdhgwbt3tutbClBU4qycls,iv:t8FmPQVlV4kjDqm/92KT+VWOAGBEv04F0wdLC1FZgHo=,tag:Dx5348l2kA8UOydhK0ryGA==,type:str]
        path: ENC[AES256_GCM,data:lv4V0g5p1ko4yq+AtD3Q6Zq1Q5RHO1ostg==,iv:YMf54SYtMb/DLIKbVY5sqxCdR8ffpDckaiKTAko0+3k=,tag:EbW4xBl5A4I95cJhrHToqg==,type:str]
        interval: ENC[AES256_GCM,data:evq96Yw=,iv:wdrM1IfRPAp40jAnWLvJtjSQ9lrA9/tIETPfvvbcne4=,tag:EwIgandhiENj8mNH4dc8Mg==,type:int]
    gfw:
        type: ENC[AES256_GCM,data:998hSw==,iv:Fqj48Spcda0uVeUMKEQ8WWZ0fpT9Q/rhbVUHlUpJ/yY=,tag:Fq1L15Yfxg9RcnrinLTF7A==,type:str]
        behavior: ENC[AES256_GCM,data:O4oMZSjT,iv:zK/yO3A2VbVA8It9Lso5n/4dcQjc5FCw6EKU17QKZzs=,tag:ZmXIdw3rCC1NsvttnpyKRg==,type:str]
        url: ENC[AES256_GCM,data:z+Pwiklw+3eoKyKXJSn/FwJ9Zfz5VKDDA9T+8luVkTBAQjvQkVUGVGLcpsX2bglUjNaQqbI2Xl1Ia/CXQXV9IvP10YStAwU=,iv:MPhAip2pnS4claHxwPdaRrCphuRIzxgzIKHSu5paJ2I=,tag:52eb/eQGs6X1I2Ds07AoAg==,type:str]
        path: ENC[AES256_GCM,data:9/6aCLUjFsf0UcNIrnK61SVr,iv:aqNcTkpGN5sysPBQeCZJv0bQCT3XSNN5n2kXe/+h1Pg=,tag:bmPBx+59Q8ZJJUar/uNLCw==,type:str]
        interval: ENC[AES256_GCM,data:0IDV/DY=,iv:yWlXRrolYCwiE0cP02rRHRebiNAT3vHevhSL/G2tgaw=,tag:PlJzQEnieTpd5GR4lxrZnQ==,type:int]
    telegramcidr:
        type: ENC[AES256_GCM,data:xwrd7A==,iv:8oncq6UdG/z9l2rvWWtytwdf17KPi7LTjqUqH7xfdTk=,tag:PKc7P+dTh/J0/zX5z7mB3A==,type:str]
        behavior: ENC[AES256_GCM,data:8iEHy7KE,iv:Iq+QXbgiTVtYQRLLv972IdqEmnVrdlXv/v3j82ACen8=,tag:fWgqOU6X/gthnsnwMAMSmg==,type:str]
        url: ENC[AES256_GCM,data:sVQDid95e6R1KV+/NCtVxv2v9Fj9he7oxLcJwYg5roYssyUXw5lKDRQ0lb5sHx/ihP/XrDID/ZY7gWEOQhYlNwva+2T+CwsjyirrKt2S1Lk=,iv:hT51/GEXDhTo3j6tow7ZTg+tNmrmNWvnfgh1X1465Tg=,tag:3V1s3ifqrp0UnMhQgHinbA==,type:str]
        path: ENC[AES256_GCM,data:PSOJpipI8z+AnJV3KtLnDptcNZSDUbQLpA2X,iv:8sx6wwTs3aoXFuZcAFwOZlbHmINnOflN9sDE4qBHzm8=,tag:VtaiIGyVcJTv0BCHwShniA==,type:str]
        interval: ENC[AES256_GCM,data:5OQoiaA=,iv:/hl6SMWsYKz5ElZ+V+1l3DxIMnj6qTE5dbVwqCGAT3k=,tag:2ZZpdfIprVU+YL+gzUuuBA==,type:int]
rules:
    - ENC[AES256_GCM,data:+X0KCn1HOVBkB9nn7NO2o90Wreb0aLBAWA==,iv:j5p6pZ31pqcQSI1GIcOcTk9/aQVsqVZ0nVCmyD2lYQE=,tag:vEY/iUfzC8IUtHYkHYr3sQ==,type:str]
    - ENC[AES256_GCM,data:vpSmBt9M6LYkFl88hun1a0pPrYu/eOYijWJK,iv:Nw6GbjVuJL+8MEPSxwlmypY5t+vqFNGDpEppG958gZw=,tag:RSN4N/fkbxXKYVLcTN6o8w==,type:str]
    - ENC[AES256_GCM,data:Pj3FnryMqGQGI5dEkf1uAApNlApl1ME4XWFjvgeO,iv:IZBruPgrZzM7pNpjD1UInhpDGRk21xDh8x4OnOcbZ5I=,tag:7td4ixcCwZsX5ovQomDBaQ==,type:str]
    - ENC[AES256_GCM,data:bJW3GzFnkxydj+KDW84fMEO4AvqZ4vXFe0qVrCw=,iv:VPsQ0b6Q2fL1zBW2KgJ0+NNg0ixlvHCyb8MX4WwlHq0=,tag:lFerpkBISBCMBjlcZKHukw==,type:str]
    - ENC[AES256_GCM,data:CkoWvQQgEcxMHzxgHsd8ehSCvrMPHsk=,iv:OAXd/S9UdZU+715xywYMjBDmzj7bJyh97RTyQn92ukc=,tag:pm8GEkaq02tzLsxmvbSn7g==,type:str]
    - ENC[AES256_GCM,data:Dto+Tj907yL6+DE0LzXeT6g2RYdvIg==,iv:XojKRdkPYdEtddEdUVrMimUXOsRKtk9spbLZhNyG8io=,tag:pNJoStJeLPX5DVrKyBSLMA==,type:str]
    - ENC[AES256_GCM,data:Amss8Oj5XKKwF7rBnQtIhVzFBuTQIxFR9Q==,iv:wPAMTztREZBQf5SESH4QzI32HMUvWLX5W3gj+2pbYoc=,tag:oVw8o2IBNNer14MkIDIk9w==,type:str]
    - ENC[AES256_GCM,data:krQFHuJaewP2uon9xqNimLTz,iv:RbtaTdpltTWrdoWbV61IpejRKcxlGlbCmnMtcDI7F4w=,tag:Y2h16Xsxkuzeon++rDhrMA==,type:str]
    - ENC[AES256_GCM,data:75esRFbgkD5o9bRdXtYk177xHJqZf07YrLi/,iv:/Anh2W3HVyweryj5UaGGft3FF8oRDyEp2G4bq9wAXeo=,tag:VnoXE2OFnPH1zqwdaAHfmA==,type:str]
    - ENC[AES256_GCM,data:grcH2Ib1/k4W4HbTjeSEApdYAqOycYeaR0z9MA==,iv:XtMrdo98HR5HrmR4IcAY5x10+hGtBDt3/rr1bz+kZnA=,tag:ch3E8eEFfxBTo7Oxouy1yw==,type:str]
    - ENC[AES256_GCM,data:fXhHqc3u+ppYiet9,iv:nIlttQeuBgxs9Z97o4MZPJTWUCWIUfNHzd/hAanweTw=,tag:4ncwTu+I5yxlKMSD8xLrvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnuydcffmwalyeqr7pmgp26nnwg4smwum05atpunh3xnfz0a5cnsc6erzf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIL2FuMUxPUEFtQ3VBTkJu
            N0ZnTWlnV1A1QkxmeFByRjUxZ0IvVUpwcW5FCmJ0Y3pUQm45R0JJR0t2WWZNTUQv
            SEtCdUJDWlBMVVlZdEtRc1NBY054RDQKLS0tIFNYam4zSGhRTks1aVltVldNdS9L
            ajJCaWI5cnU3MDc5a0tpcFp6ZnRyZUkKxP8jP84sj5JVABDTXuvCChUE/FjbIo1C
            74+MVlL1i3razYJXx/f2G1HCD3GuK90V/yc+xoChoMMCDuZwh4xG4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1efdgqxst6zk3vysvnmrexuh9csqwz9nwhtr9uyp77xn8epddvcuskq8y9v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvelVsMGRHTUFkUTNYWElv
            c0UyWFluZnVYWGdsRlJIR0VMRVhSODVOOUMwCjdQYWRPN0krZ05qcGltbUNrL3dD
            QkVhTFRhTzA3cGNFT3VGS2dsU0NPL2sKLS0tIFQyTVdWZDF4NjYzNXlwblNRc1J2
            aFplck5WdStKUFpEUVExK2ZYelgzY3MK99jIKzphQWYl5aCSEYXjHpteYmStkWz+
            3NPJYicYptOKJTtfUqRSYTl53orhwRQyMxTFdgdDhKvHpVuv8ZOlcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-29T11:13:37Z"
    mac: ENC[AES256_GCM,data:MnHKIRiS6wi6KNTtk8+nxoyZESB26DHtKp2pO94JMaltS72XF3va9Zxl5cqZF/xQFboPH93fDAdVeN2TgMOMnB7OxQcWNN+5Yri6Pn5Hid4mM5FZmDDeXYeQBKKOC1FslnbOuGO/d8mcPcTAdLvlJoBFU3oD3BAS/d1hhe2ZrUo=,iv:byWXSQyJ7BMO22dx9ObPlOsMkqYYjk3ZbWAruXTSgUg=,tag:CWjyX8yj+IJVLEnPlGF8jQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
